### ISSUE TITLE
How to install opscale in ubuntu?

### ISSUE THREAD

**Issue by KiranPrajapati345** [alubbock/pyopscale#1] opened 2017-03-16 06:59 UTC
I have search in google, but I don't get anywhere how to install opscale package . I am using ubuntu-16.04 , when I use command  
1) "pip install opscale" 
2) "pip install pyopscale"
3) "pip install Opscale "

Not installed yet.
so,how to installed this package?
And I have data x1,x2,....x10 (independent variables are in level), so using opscale package i have get single value with numeric , right? and using this numeric value , can I apply regression analysis for predict dependent variable?

**Comment by alubbock** [comment] 2017-03-26 23:14
I haven't used worked on this package in a while, but I've updated the [readme](https://github.com/alubbock/pyopscale) with installation details, I hope that helps? pyopscale is a just small wrapper around the R package opscale, so [their documentation](http://polisci.msu.edu/jacoby/icpsr/scaling/computing/alsos/Jacoby,%20opscale%20MS.pdf) should help with any questions about usage. This package just wraps their `opscale` function in Python.

**Comment by KiranPrajapati345** [comment] 2017-03-27 05:02
Using this command : 
 pip install git+git://github.com/alubbock/pyopscale.git

it will install but when I run 

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> from pyopscale.opscale import OpScale
>>> x1 = [1,1,1,1,2,2,2,3,3,3,3,3,3]
>>> x2 = [3,2,2,2,1,2,3,4,5,2,6,6,4]
>>> os = OpScale()

Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning: Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection


Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning: In addition: 

Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning: Warning message:


Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning: In file(filename, "r", encoding = encoding) :

Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning: 
 

Warning (from warnings module):
  File "/usr/local/lib/python2.7/dist-packages/rpy2/rinterface/__init__.py", line 186
    warnings.warn(x, RRuntimeWarning)
RRuntimeWarning:  cannot open file '/usr/local/lib/python2.7/dist-packages/pyopscale/opscale.R': No such file or directory


Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    os = OpScale()
  File "/usr/local/lib/python2.7/dist-packages/pyopscale/opscale.py", line 10, in __init__
    __file__), os.path.sep))
  File "/usr/local/lib/python2.7/dist-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection 


it will give me this error .
>>> os = OpScale()  ### this is not works
:(

**Comment by alubbock** [comment] 2017-10-18 22:49
Sorry for the (very) delayed reply. Your error was caused by the R script not installing properly, which should now be fixed if you reinstall the package (you might need to use `pip install --upgrade`). I'll close the issue, but please do contact me again if you have any further problems, and I'll be sure to respond faster next time!

**Closed as completed by alubbock** 2017-10-18 22:49 UTC
